{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    distrobox
    git
    greetd.tuigreet
    greetd.gtkgreet
    greetd.wlgreet
    libnotify
    lshw
    lutris-free
    micro
    neofetch
    networkmanagerapplet
    nil
    nixfmt-rfc-style
    ntfs3g
    parted
    pavucontrol
    polkit
    pulseaudio
    udiskie
    udisks
    ungoogled-chromium
    usbutils
    wget
    wineWowPackages.waylandFull
    wireshark
    angryipscanner
    bzip2
    system-config-printer
    magic-wormhole-rs
    wireguard-tools
    sshfs
    rclone
  ];
}
#
