{ ... }:
{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./docker.nix
    ./fonts.nix
    ./greetd.nix
    ./keyboard.nix
    ./keyring.nix
    ./laptop.nix
    ./locale.nix
    ./lsfg.nix
    ./mount.nix
    ./networking.nix
    ./nh.nix
    #./niri.nix
    ./nm-applet.nix
    ./nvidia.nix
    ./polkit.nix
    ./printing.nix
    ./retroarch.nix
    ./ssh.nix
    ./sway.nix
    #./tailscale.nix
    ./tlp.nix
    ./video.nix
    ./vms.nix
    ./vnstat.nix
    ./vpn.nix
    ./wireguard.nix
  ];
}
